# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme_day: minimal 
theme_night: minimal
font: minimal
font_size: L

# SEO (Search Engine Optimization: https://wowchemy.com/docs/hugo-tutorials/seo/)

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'A highly-customizable Hugo academic resume theme powered by Wowchemy website builder.'
    twitter: 'wowchemy'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true
    
# Site footer

footer:
  copyright:
    notice: 'Â© 2022 Margot Wagner'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: true
  diagram: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/margotwagner/my-website-academic/'
    content_dir: content
    branch: master
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15
    
# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  isotope:
    # Enable if you use the Portfolio widget or Publication filter
    enable: true
  academicons:
    enable: true
